name: Push Source Files to Applanga
on:
  push:
    branches:
      - master
    paths:
      - package.json
  workflow_dispatch:
    inputs:
      push_targets:
        type: boolean
        description: Push translation files. If set translation files will be pushed instead of source files
        default: false
        required: false
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          path: checkout
      - uses: applanga/setup-applanga-cli@v1.0.4
        with:
          version: 1.0.*
      - name: Push Sources to Applanga
        if: '${{ inputs.push_targets != true }}'
        env:
          APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
        run: applanga --debug push --force
        working-directory: checkout
      - name: Push Translation Files to Applanga
        if: '${{ inputs.push_targets == true }}'
        env:
          APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
        run: applanga --debug pushtarget
        working-directory: checkout
